name: Docker build & push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: projet7fastapi.azurecr.io
          username: ${{ secrets.AZURE_ECR_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: projet7fastapi.azurecr.io/api:latest

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: oc_projet7
          image: projet7fastapi.azurecr.io/api:latest
          registry-username: ${{ secrets.AZURE_ECR_USERNAME }}
          registry-password: ${{ secrets.AZURE_PASSWORD_TOKEN }}
          name: api
          location: 'France Central'